title:
  patterns:
    - '^.{20}'
  error: The title must be 20 characters or more
body:
  patterns:
    - '\[x\](.|\s)*https:\/\/app.clickup.com'
  error: You must indicate your pull request type or set clickup link task
version: 1