name: CI
on:
pull_request:
  types: ['opened','edited','reopened','synchronize','review_requested','review_request_removed','assigned','unassigned','labeled','unlabeled']
  push: []
jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"