name: PR Linter
on:
  pull_request:
    types: ['opened','edited','reopened','synchronize','review_requested','review_request_removed','assigned','unassigned','labeled','unlabeled']


jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: innerspacetrainings/Prace.js@master
        with:
          configuration-path: .github/pr-linter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
